package Vista;

import Logica.Estudiante;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;

public class JFAddEstudiante extends javax.swing.JFrame {
    JTable tabla;
    Estudiante estudiante;
    /**
     * Creates new form JFAddEstudiante
     */
    public JFAddEstudiante(JTable tabla) {
        initComponents();
//        this.setAlwaysOnTop(true);
        this.setLocationRelativeTo(null);
        this.tabla = tabla;
        this.estudiante = new Estudiante();
        estudiante.actualizarTabla(tabla);
    }

    private JFAddEstudiante() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFNombres = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTFApellidos = new javax.swing.JTextField();
        btnCancelarStud = new javax.swing.JButton();
        btnAceptaEstud = new javax.swing.JButton();

        setTitle("Añadir Estudiante");

        jLabel4.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel4.setText("AÑADIENDO ESTUDIANTE");

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel1.setText("Código");

        jTFCodigo.setEditable(false);

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Nombres");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        btnCancelarStud.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarStud.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCancelarStud.setText("Cancelar");
        btnCancelarStud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarStudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarStudMouseExited(evt);
            }
        });
        btnCancelarStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarStudActionPerformed(evt);
            }
        });

        btnAceptaEstud.setBackground(new java.awt.Color(255, 255, 255));
        btnAceptaEstud.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnAceptaEstud.setText("Aceptar");
        btnAceptaEstud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAceptaEstudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAceptaEstudMouseExited(evt);
            }
        });
        btnAceptaEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptaEstudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTFApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(jTFNombres, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(115, 115, 115))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptaEstud, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelarStud, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptaEstud, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarStud, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptaEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptaEstudActionPerformed
        estudiante = new Estudiante(this.jTFNombres.getText(), this.jTFApellidos.getText());
        boolean flag = estudiante.añadirEstudiante();
        if(flag){
               JOptionPane.showMessageDialog(null, "Datos Guardados correctamente.");
            tabla = estudiante.actualizarTabla(tabla);
            comewth();
        }else{
            JOptionPane.showMessageDialog (null, "Ocurrio un error al ingresar los datos ");   
        }
    }//GEN-LAST:event_btnAceptaEstudActionPerformed

    private void btnCancelarStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarStudActionPerformed
        this.dispose();
        comewth();
    }//GEN-LAST:event_btnCancelarStudActionPerformed

    private void btnAceptaEstudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptaEstudMouseEntered
        this.btnAceptaEstud.setBorder(new LineBorder(Color.red));
        this.btnAceptaEstud.setForeground(Color.red);
    }//GEN-LAST:event_btnAceptaEstudMouseEntered

    private void btnAceptaEstudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptaEstudMouseExited
        this.btnAceptaEstud.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnAceptaEstud.setForeground(Color.black);
    }//GEN-LAST:event_btnAceptaEstudMouseExited

    private void btnCancelarStudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarStudMouseEntered
        this.btnCancelarStud.setBorder(new LineBorder(Color.red));
        this.btnCancelarStud.setForeground(Color.red);
    }//GEN-LAST:event_btnCancelarStudMouseEntered

    private void btnCancelarStudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarStudMouseExited
        this.btnCancelarStud.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnCancelarStud.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelarStudMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFAddEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFAddEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFAddEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFAddEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFAddEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptaEstud;
    private javax.swing.JButton btnCancelarStud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFNombres;
    // End of variables declaration//GEN-END:variables
    
    public void comewth(){
        this.jTFCodigo.setText("");
        this.jTFNombres.setText("");
        this.jTFApellidos.setText("");
    }
}
