/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.sql.*;
import Logica.Cliente;
import java.awt.Color;
import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class JFEditCliente extends javax.swing.JFrame {
JTable tabla;
Cliente cliente;
    public JFEditCliente(JTable tabla) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tabla = tabla;
        this.cliente = new Cliente();
        cliente.actualizarTabla(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jCNombresEstudiante = new javax.swing.JCheckBox();
        jCApellidosEstudiante = new javax.swing.JCheckBox();
        jTFCedulaClienteActualizar = new javax.swing.JTextField();
        jTFTelefonoClienteaActualizar = new javax.swing.JTextField();
        jTFDireccionClienteaActualizar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtableClientes = new javax.swing.JTable();
        comboBoxBusquedaCliente = new javax.swing.JComboBox<>();
        jTFBusquedaCliente = new javax.swing.JTextField();
        btnActualizarEstud = new javax.swing.JButton();
        btnEliminarEstud = new javax.swing.JButton();
        btnCancelatStud2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Actualizar y eliminar Estudiante");

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos a actualizar"));

        jCNombresEstudiante.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jCNombresEstudiante.setText("Telefono");
        jCNombresEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCNombresEstudiante.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCNombresEstudianteStateChanged(evt);
            }
        });
        jCNombresEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCNombresEstudianteActionPerformed(evt);
            }
        });

        jCApellidosEstudiante.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jCApellidosEstudiante.setText("Direccion");
        jCApellidosEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCApellidosEstudiante.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCApellidosEstudianteStateChanged(evt);
            }
        });

        jTFCedulaClienteActualizar.setEditable(false);

        jTFTelefonoClienteaActualizar.setEditable(false);

        jTFDireccionClienteaActualizar.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel3.setText("Cedula");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCApellidosEstudiante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCNombresEstudiante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFDireccionClienteaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFTelefonoClienteaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTFCedulaClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFCedulaClienteActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCNombresEstudiante)
                    .addComponent(jTFTelefonoClienteaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCApellidosEstudiante)
                    .addComponent(jTFDireccionClienteaActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        jtableClientes.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jtableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Código Sede", "Nombre", "Telefono", "Dirección", "Ubicación"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableClientesMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jtableClientes);

        comboBoxBusquedaCliente.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        comboBoxBusquedaCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cedula", "nombre", " " }));
        comboBoxBusquedaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxBusquedaClienteActionPerformed(evt);
            }
        });

        jTFBusquedaCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBusquedaClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(comboBoxBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTFBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        btnActualizarEstud.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnActualizarEstud.setText("Actualizar");
        btnActualizarEstud.setPreferredSize(new java.awt.Dimension(107, 51));
        btnActualizarEstud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarEstudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarEstudMouseExited(evt);
            }
        });
        btnActualizarEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarEstudActionPerformed(evt);
            }
        });

        btnEliminarEstud.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnEliminarEstud.setText("Eliminar");
        btnEliminarEstud.setPreferredSize(new java.awt.Dimension(107, 51));
        btnEliminarEstud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEliminarEstudMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEliminarEstudMouseExited(evt);
            }
        });
        btnEliminarEstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEstudActionPerformed(evt);
            }
        });

        btnCancelatStud2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCancelatStud2.setText("Cancelar");
        btnCancelatStud2.setPreferredSize(new java.awt.Dimension(62, 25));
        btnCancelatStud2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelatStud2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelatStud2MouseExited(evt);
            }
        });
        btnCancelatStud2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelatStud2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("ACTUALIZAR Y ELIMINAR CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnActualizarEstud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(btnEliminarEstud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(btnCancelatStud2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelatStud2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarEstud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarEstud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEstudActionPerformed
        ArrayList<String> atributosActualizar = new ArrayList<String>();
        String consulta = "";
        atributosActualizar.add("CEDULACLIENTE="+jTFCedulaClienteActualizar.getText());
        if (jCNombresEstudiante.isSelected()){atributosActualizar.add("nombres_e='"+jTFTelefonoClienteaActualizar.getText()+"'");}
        if (jCApellidosEstudiante.isSelected()){atributosActualizar.add("apellidos_e='"+jTFDireccionClienteaActualizar.getText()+"'");}
        
        Iterator<String> i = atributosActualizar.iterator();
        while (i.hasNext()){
            consulta += i.next() +",";
        }
        
        consulta = consulta.substring (0, consulta.length()-1);
        String condicion = "'" +jTFCedulaClienteActualizar.getText() + "'";
        
        String sql = "UPDATE V_clientes SET "+ consulta + " WHERE codigo_e " + " LIKE "+condicion;

        if(cliente.actualizarCliente(sql))
            JOptionPane.showMessageDialog(null, "Datos Actualizados correctamente. ");
        else{
            JOptionPane.showMessageDialog (null, "Ocurrio un error al Actualizar los datos ");  
        }

        cliente.actualizarTabla(tabla);      
        cliente.actualizarTablaBusqueda(jtableClientes, getConsulta());

    }//GEN-LAST:event_btnActualizarEstudActionPerformed

    private void jtableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableClientesMouseClicked
        int row =jtableClientes.getSelectedRow();
        if (row !=-1 ){
            jTFCedulaClienteActualizar.setText(Integer.toString((int)jtableClientes.getValueAt(row, 0)));
            jTFTelefonoClienteaActualizar.setText((String)jtableClientes.getValueAt(row, 1));
            jTFDireccionClienteaActualizar.setText((String)jtableClientes.getValueAt(row, 2));
        }
    }//GEN-LAST:event_jtableClientesMouseClicked

    private void btnEliminarEstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEstudActionPerformed
        if(0==JOptionPane.showConfirmDialog(null, "¿Esta seguro de borrar "+jTFTelefonoClienteaActualizar.getText()+" ?","Advertencia",JOptionPane.INFORMATION_MESSAGE)){
            cliente.setCedula(jTFCedulaClienteActualizar.getText());
    
        if(cliente.eliminarCliente())
            JOptionPane.showMessageDialog(null, "Registro eliminado correctamente.");
        else{
            JOptionPane.showMessageDialog (null, "Ocurrio un error al eliminar los datos ");
        }     
            jTFCedulaClienteActualizar.setText("");
            jTFTelefonoClienteaActualizar.setText("");
            jTFDireccionClienteaActualizar.setText("");       
            cliente.actualizarTabla(tabla);
        }
    }//GEN-LAST:event_btnEliminarEstudActionPerformed

    private void btnCancelatStud2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelatStud2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelatStud2ActionPerformed

    private void jTFBusquedaClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBusquedaClienteKeyReleased
        cliente.actualizarTablaBusqueda(jtableClientes, getConsulta());
    }//GEN-LAST:event_jTFBusquedaClienteKeyReleased

    private void btnActualizarEstudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEstudMouseEntered
        this.btnActualizarEstud.setBorder(new LineBorder(Color.red));
        this.btnActualizarEstud.setForeground(Color.red);
    }//GEN-LAST:event_btnActualizarEstudMouseEntered

    private void btnActualizarEstudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarEstudMouseExited
        this.btnActualizarEstud.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnActualizarEstud.setForeground(Color.black);
    }//GEN-LAST:event_btnActualizarEstudMouseExited

    private void btnEliminarEstudMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEstudMouseEntered
        this.btnEliminarEstud.setBorder(new LineBorder(Color.red));
        this.btnEliminarEstud.setForeground(Color.red);
    }//GEN-LAST:event_btnEliminarEstudMouseEntered

    private void btnEliminarEstudMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarEstudMouseExited
        this.btnEliminarEstud.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnEliminarEstud.setForeground(Color.black);
    }//GEN-LAST:event_btnEliminarEstudMouseExited

    private void btnCancelatStud2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelatStud2MouseEntered
        this.btnCancelatStud2.setBorder(new LineBorder(Color.red));
        this.btnCancelatStud2.setForeground(Color.red);
    }//GEN-LAST:event_btnCancelatStud2MouseEntered

    private void btnCancelatStud2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelatStud2MouseExited
        this.btnCancelatStud2.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnCancelatStud2.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelatStud2MouseExited

    private void comboBoxBusquedaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxBusquedaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxBusquedaClienteActionPerformed

    private void jCApellidosEstudianteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCApellidosEstudianteStateChanged
        Checkboxcambio(jCApellidosEstudiante, jTFDireccionClienteaActualizar);
    }//GEN-LAST:event_jCApellidosEstudianteStateChanged

    private void jCNombresEstudianteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCNombresEstudianteStateChanged
        Checkboxcambio(jCNombresEstudiante, jTFTelefonoClienteaActualizar);
    }//GEN-LAST:event_jCNombresEstudianteStateChanged

    private void jCNombresEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCNombresEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCNombresEstudianteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarEstud;
    private javax.swing.JButton btnCancelatStud2;
    private javax.swing.JButton btnEliminarEstud;
    private javax.swing.JComboBox<String> comboBoxBusquedaCliente;
    private javax.swing.JCheckBox jCApellidosEstudiante;
    private javax.swing.JCheckBox jCNombresEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTFBusquedaCliente;
    private javax.swing.JTextField jTFCedulaClienteActualizar;
    private javax.swing.JTextField jTFDireccionClienteaActualizar;
    private javax.swing.JTextField jTFTelefonoClienteaActualizar;
    private javax.swing.JTable jtableClientes;
    // End of variables declaration//GEN-END:variables

public void Checkboxcambio(javax.swing.JCheckBox jCheckBox, javax.swing.JTextField jTField ){
        if(jCheckBox.isSelected()){
            jTField.setEditable(true);
        }else{
             jTField.setEditable(false);
        }
}

public String getConsulta(){
        String consulta = "";
        switch(comboBoxBusquedaCliente.getSelectedIndex()){
            case 0:
                consulta="cedula='"+jTFBusquedaCliente.getText(); 
                break;
            case 1:
                consulta="nombre='"+jTFBusquedaCliente.getText()+"'"; 
                break;
        }
        
        return consulta;

}
}
