/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Logica.Cliente;
import Logica.Libro;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.border.LineBorder;

/**
 *
 * @author PC
 */
public class JFModificarLibro extends javax.swing.JFrame {
Libro libro;
JTable tabla;
    public JFModificarLibro(JTable tabla) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tabla = tabla;
        this.libro = new Libro();
        libro.actualizarTabla(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jCPrecio = new javax.swing.JCheckBox();
        jTFISBNLibroActualizar = new javax.swing.JTextField();
        jTFPrecioLibActu = new javax.swing.JTextField();
        jTFCantidadActualizarLibros = new javax.swing.JTextField();
        jCCantidadLibro = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jCBusquedaLibro = new javax.swing.JComboBox<>();
        jTFBusquedaLibro = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTBusquedaAct = new javax.swing.JTable();
        btnActualizarLib = new javax.swing.JButton();
        btnCancelarLib = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Actualizar y eliminar Libros");

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Atributos a actualizar"));

        jCPrecio.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jCPrecio.setText("Precio");
        jCPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCPrecio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCPrecioStateChanged(evt);
            }
        });

        jTFISBNLibroActualizar.setEditable(false);

        jTFPrecioLibActu.setEditable(false);

        jTFCantidadActualizarLibros.setEditable(false);

        jCCantidadLibro.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jCCantidadLibro.setText("Cantidad");
        jCCantidadLibro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCCantidadLibro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCCantidadLibroStateChanged(evt);
            }
        });
        jCCantidadLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCCantidadLibroActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jTFISBNLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jCPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFPrecioLibActu, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jCCantidadLibro)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCantidadActualizarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFISBNLibroActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCCantidadLibro)
                    .addComponent(jTFCantidadActualizarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCPrecio)
                    .addComponent(jTFPrecioLibActu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        jCBusquedaLibro.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jCBusquedaLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISBN", "nombre", "genero" }));
        jCBusquedaLibro.setSelectedIndex(-1);

        jTFBusquedaLibro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFBusquedaLibroKeyReleased(evt);
            }
        });

        jTBusquedaAct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ISBN", "Titulo", "Autor", "Género", "Año", "Editorial", "Cantidad", "Precio", "Ubicacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTBusquedaAct);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 188, Short.MAX_VALUE)
                        .addComponent(jCBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jTFBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTFBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBusquedaLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnActualizarLib.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnActualizarLib.setText("Actualizar");
        btnActualizarLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnActualizarLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnActualizarLibMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnActualizarLibMousePressed(evt);
            }
        });
        btnActualizarLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarLibActionPerformed(evt);
            }
        });

        btnCancelarLib.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        btnCancelarLib.setText("Cancelar");
        btnCancelarLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarLibMouseExited(evt);
            }
        });
        btnCancelarLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarLibActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 24)); // NOI18N
        jLabel1.setText("ACTUALIZAR Y ELIMINAR LIBROS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(429, 429, 429)
                        .addComponent(btnActualizarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnCancelarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizarLib, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCPrecioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCPrecioStateChanged
        Checkboxcambio(jCPrecio, jTFPrecioLibActu);
    }//GEN-LAST:event_jCPrecioStateChanged

    private void jCCantidadLibroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCCantidadLibroStateChanged
        Checkboxcambio(jCCantidadLibro, jTFCantidadActualizarLibros);
    }//GEN-LAST:event_jCCantidadLibroStateChanged

    private void jCCantidadLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCCantidadLibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCCantidadLibroActionPerformed

    private void btnActualizarLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarLibActionPerformed
        ArrayList<String> atributosActualizar = new ArrayList<String>();

        String consulta = "";
        atributosActualizar.add("ISBN="+jTFISBNLibroActualizar.getText());
        if (jCPrecio.isSelected()){atributosActualizar.add("precio='"+jTFPrecioLibActu.getText()+"'");}
        if (jCCantidadLibro.isSelected()){atributosActualizar.add("cantidad='"+jTFCantidadActualizarLibros.getText()+"'");}

        Iterator<String> i = atributosActualizar.iterator();

        while (i.hasNext()){
            consulta += i.next() +",";
        }
        consulta = consulta.substring (0, consulta.length()-1);
        String condicion = "'" +jTFISBNLibroActualizar.getText () + "'";
        String sql = "UPDATE V_Ejemplar SET "+ consulta + " WHERE ISBN" + " LIKE "+condicion;


        if(libro.actualizarLibro(sql))
            JOptionPane.showMessageDialog(null, "Datos Actualizados correctamente. ");
        else{
            JOptionPane.showMessageDialog (null, "Ocurrio un error al Actualizar los datos ");  
        }
        
        libro.actualizarTabla(tabla);
        libro.ActualizarTablaLibrosBusqueda(jTBusquedaAct, getConsulta());
    }//GEN-LAST:event_btnActualizarLibActionPerformed

    private void jTFBusquedaLibroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFBusquedaLibroKeyReleased
        libro.ActualizarTablaLibrosBusqueda(jTBusquedaAct, getConsulta());
    }//GEN-LAST:event_jTFBusquedaLibroKeyReleased

    private void btnCancelarLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarLibActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_btnCancelarLibActionPerformed

    private void btnActualizarLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarLibMouseEntered
        this.btnActualizarLib.setBorder(new LineBorder(Color.red));
        this.btnActualizarLib.setForeground(Color.red);
    }//GEN-LAST:event_btnActualizarLibMouseEntered

    private void btnActualizarLibMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarLibMousePressed

    }//GEN-LAST:event_btnActualizarLibMousePressed

    private void btnCancelarLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarLibMouseEntered
        this.btnCancelarLib.setBorder(new LineBorder(Color.red));
        this.btnCancelarLib.setForeground(Color.red);
    }//GEN-LAST:event_btnCancelarLibMouseEntered

    private void btnCancelarLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarLibMouseExited
        this.btnCancelarLib.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnCancelarLib.setForeground(Color.black);
    }//GEN-LAST:event_btnCancelarLibMouseExited

    private void btnActualizarLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarLibMouseExited
        this.btnActualizarLib.setBorder(new LineBorder(new Color(90,130,191)));
        this.btnActualizarLib.setForeground(Color.black);
    }//GEN-LAST:event_btnActualizarLibMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarLib;
    private javax.swing.JButton btnCancelarLib;
    private javax.swing.JComboBox<String> jCBusquedaLibro;
    private javax.swing.JCheckBox jCCantidadLibro;
    private javax.swing.JCheckBox jCPrecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTBusquedaAct;
    private javax.swing.JTextField jTFBusquedaLibro;
    private javax.swing.JTextField jTFCantidadActualizarLibros;
    private javax.swing.JTextField jTFISBNLibroActualizar;
    private javax.swing.JTextField jTFPrecioLibActu;
    // End of variables declaration//GEN-END:variables

    public void Checkboxcambio(javax.swing.JCheckBox jCheckBox, javax.swing.JTextField jTField ){
        if(jCheckBox.isSelected()){
            jTField.setEditable(true);
        }else{
             jTField.setEditable(false);
        }
}
    public String getConsulta(){
     String consulta = "";
        switch(jCBusquedaLibro.getSelectedIndex()){
            case 0:
                consulta="codigo_l="+jTFBusquedaLibro.getText(); 
                break;
            case 1:
                consulta="nombre='"+jTFBusquedaLibro.getText()+"'"; 
                break;
            case 2: 
                consulta="genero='"+jTFBusquedaLibro.getText()+"'";
                break;
        
        }
        return consulta;
    }
}
